'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'

interface CampaignData {
    name: string;
    description: string;
    cta: string;
    commission: number; // Parsed from string
    providerId?: string; // Optional, inferred from auth
}

export async function createCampaign(data: CampaignData) {
    const supabase = createClient()

    // 1. Get current user
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return { error: 'Not authenticated' }
    }

    // 2. Validate data
    if (!data.name || !data.description || !data.commission) {
        return { error: 'Missing required fields' };
    }

    // 3. Insert into DB (Table 'Campaign')
    // Note: We need to mapped field names to schema.prisma
    // schema: name, description, commission, cta, providerId, isActive

    const { error } = await supabase
        .from('Campaign')
        .insert({
            name: data.name,
            description: data.description,
            commission: data.commission,
            cta: data.cta,
            providerId: user.id,
            isActive: true,
            updatedAt: new Date().toISOString() // Manual timestamp if not auto-generated by Supabase trigger, usually Prisma handles this but Supabase direct insert might need it or default
        })

    if (error) {
        console.error('Campaign creation error:', error)
        return { error: error.message }
    }

    revalidatePath('/dashboard/provider')
    return { success: true }
}

export async function getAvailableCampaigns() {
    const supabase = createClient()

    // Fetch all active campaigns
    const { data: campaigns, error } = await supabase
        .from('Campaign')
        .select(`
            *,
            provider:providerId (
                name
            )
        `)
        .eq('isActive', true)
        .order('createdAt', { ascending: false })

    if (error) {
        console.error('Error fetching campaigns:', error)
        return []
    }

    return campaigns
}
